threeML/astromodels

astromodels/functions/functions.py
setup.py

This fixes a gfortran lookup for OS X. Users installing gfortran via home-brew have gfortran under /usr/local/gfortran/lib 
There were a couple of complaints about it and I was manually hacking the setup file. However, this looks for gfortran in the standard places and as a last resort looks for the home-brew version.

adding additoonal search paths for gfortran because: OS X

---

astromodels/functions/function.py

When using linked parameters, the return of the parameter.value member seems to always be a 0-D array. I'm not sure if there is a reason for this, but it was confusing the hashing of a tuple.
I've made an explicit cast to float when creating the unique_id. This should fix #25

fixed hashing of linked parameters

---

astromodels/xspec/factory.py

single value calls were crashing the code. this fixes that.

keep final_value as array so rev_idx works

---

astromodels/functions/template_model.py
astromodels/tests/test_template_model.py

I noticed that 1D template models were failing due to a map. I added a check to expand the dimension as needed.

1D templates were failing. added np.atleast_1d to fix

---

astromodels/functions/functions_2D.py

Two proposed changes to SpatialTemplate_2D in astromodels.functions.functions_2D:
1. Fix map access (X/Y coordinates were switched)
2. Use astropy.wcs to handle coordinate transformations between RA/Dec and the fits map; this is more accurate and more robust (allows to input templates in arbitrary* coordinate systems/projections as long as they conform to fits standards)
*healpix templates not currently supported.

2D spatial templates 

---

astromodels/functions/functions_2D.py
astromodels/functions/functions_3D.py

This pull request includes the following implementations:
1. add get_boundaries() for Lataitude_Galactic_Diffuse (temporary solution, will edit LIFF so we can completely get rid of get_boundaries())
2. add powerLaw_on_sphere function to define a 1/r^n morphology
3. in Continuous_injection_diffusion, change uratio to b (magnetic field) so it is more clear what it is, also add parameter rinj to define energy-dependent diffusion radius limited by the injection time (age).
4. add Continuous_injection_diffusion_ellipse, which is an asymmetric diffusion model.

A few 2D and 3D functions

---

astromodels/functions/functions_2D.py

A bug found by Henrike on the normalization of the function2D power_law_on_shpere(). It affects the spectral normalization but not spectral index, spatial index or best fit TS.

fix bug on norm in power_law_on_sphere

---

astromodels/core/model_parser.py
astromodels/functions/functions.py
astromodels/functions/functions_2D.py
astromodels/tests/test_extended_source.py
astromodels/tests/test_point_source.py

Fixed the issue where map information was lost when cloning a 2D template function instance. As suggested by @giacomov , the path to the fits file is saved rather than the map itself. So, the user needs to make sure that the fits file is still available when the model is cloned or loaded from a yml file.
Also added some more tests for functions (made sure they return the same value after being cloned) and made all functions calls work with and without units so all current tests pass.

Fix Cloning 2Dtemplate model, fix units in some functions

---

astromodels/sources/extended_source.py
astromodels/sources/particle_source.py
astromodels/sources/point_source.py

See discussion https://github.com/threeML/astromodels/pull/99 and https://github.com/threeML/astromodels/issues/98
I changed the parameters() and free_parameters() functions of point_source.py and extended_source.py to use the parameter path, rather than its name, as a key.
(I also added parameters() properties to the point source and particle source classes).
I ran some tests to make sure everything works locally... It doesn't seem to affect the tests and I can ~not~ _now_ fit the offending gaussian galactic diffuse emission source.

use parameter path rather than name as dictionary key

---

.travis.yml
astromodels/functions/template_model.py
astromodels/tests/test_template_model.py
conda-dist/recipe/meta.yaml
setup.cfg

This switches some of the interpolators in table models from scipy to the numba based https://github.com/EconForge/interpolation.py
Speed tests have shown a speed up of ~50x on an array of 100 energies and ~30x on an array of 1000 energies. This is from a scipy runtime of about 11ms to a numba runtime of 300 mus. 
The interpolation no long supports python2 so I have done some tricks that mean the numba versions are only used for py3. Additionally, this will drop support for 3.5 and 3.6 as well as turn of the no xspec builds. 
I will likely have to do some merging to get this inline with #121

Numba interp

---

astromodels/functions/functions.py

Add a default minimum for the cutoff energy in the cutoff_powerlaw function to avoid this warning:
```
$ python -c "import astromodels"
/Users/ich/hawc_software/miniconda3/envs/clean_hal/lib/python2.7/site-packages/astromodels/core/parameter.py:555: UserWarning: We have set the min_value of xc to 1e-99 because there was a postive transform
warnings.warn('We have set the min_value of %s to 1e-99 because there was a postive transform' % self.path)
```
when loading astromodels.
Btw, I notice that `Cutoff_powerlaw.xc` has a log10 transform, but `Super_cutoff_powerlaw.xc` and `Exponential_cutoff.xc` do not. Is that intentional?

set default minimum for cutoff parameter; fix comments

---

astromodels/tests/test_1D_function_values.py
astromodels/tests/test_point_source.py

This is just a small update to the tests. I was seeing two errors related to the EBLattenuation function, see below. These would only show up if you have the [ebltable](https://github.com/me-manu/ebltable) installed, which is optional. In any case, EBLattenuation isn't contained in the file with prior function values, so I removed it from that test. I also removed it from `test_call_with_units` in `test_point_source.py` since it cannot be used as a spectrum, and added it to `test_call_with_composite_function_with_units` instead. 
Log file with pytest failures before applying this fix: 
[failures.txt](https://github.com/threeML/astromodels/files/5031617/failures.txt)

Update tests: special treatment for EBLattenuation function

---

astromodels/core/model_parser.py
astromodels/functions/function.py
astromodels/tests/test_template_model.py
astromodels/xspec/include/sherpa/astro/xspec_extension.hh
astromodels/xspec/include/sherpa/extension.hh
astromodels/xspec/src/_xspec.cc
build_local.sh
ci/build_and_test.sh
conda-dist/no_xspec_recipe/meta.yaml
conda-dist/recipe/meta.yaml
setup.cfg

- xspec related code updated to be compliant with `xspec-modelsonly=6.25`
- removed pinned dependency `pyyaml`=3.13 (now `pyyaml>=5.1`)
- now compatible with newer versions of `astropy`

Root6 compatibility

---

conda-dist/recipe/meta.yaml
setup.cfg

I have removed PyTables as it seems to not be used and is causing issues with pip installs. @ndilalla can you double check that we aren't using it anywhere?

remove pytables to see if tests pass

---

setup.py

Adds a better way to find the XSPEC header files in they are not in /usr/local/include
The user can set an env var, XSPEC_INC_PATH, but it also makes and assumption that the path is one up from the libraries plus include. Thus, it should work now.
I tested on linux machine that was having issues.

Xspec setup

---

astromodels/core/model_parser.py
astromodels/core/sky_direction.py

So I was having issues when fitting a point source with free position. I tracked it down to the fact that bounds on the point source position are 'lost' when loading a model from a yml file (I'm loading my input models from yml before starting the fit). 
The same thing happens when cloning the model, for example to compute the TS of each source.
Turns out that in `model_parser.py` and `sky_direction.py`, the bounds were forced to be 0 t0 360 for the right ascension and -90 to 90 for the declination, overwriting user-set bounds.
This is my attempt to fix it. Tests pass on my laptop. Was there a deeper reason for over-writing source position bounds? This did not seem to happen for extended sources, btw.

Stop overwriting point source position bounds when parsing model

---

astromodels/functions/function.py

Trivial update: This pull request adds a `has_free_parameters` property to the astromodels functions class, so we can easily check if e.g. a source's spectrum or spatial shape has free parameters.

Convenience function: has_free_parameters for astromodels functions

---

astromodels/tests/test_load_xspec_models.py

adds a small test to make sure that xspec models can be reloaded.

Ensure xspec models known

---

astromodels/functions/template_model.py

By specifying the dtype for the grid array in the interpolator the numba typing error is resolved.

Fix for Issue #172

---

astromodels/core/parameter.py

The internal_delta calculation would fail in case there was a transform but no boundaries had been set on the parameter.

Fix internal delta calculation in case of no bounds

---

.github/workflows/docs.yml
.github/workflows/test_and_build.yml
astromodels/functions/functions_1D/powerlaws.py
ci/environment.yml
docs/requirements.txt
setup.cfg

We updated all the workflows to use python 3.9, 3.10, and 3.11.
Update readthedoc file

Update workflow and doc

---

versioneer.py

From [Python 12 release notes](https://docs.python.org/3/whatsnew/3.12.html)
> [configparser](https://docs.python.org/3/library/configparser.html#module-configparser) no longer has a SafeConfigParser class. Use the shorter [ConfigParser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser) name instead.
>[configparser.ConfigParser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser) no longer has a readfp method. Use [read_file()](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read_file) instead.
I changed those names, and now it works. These were marked as deprecated since Python 3.2, so this change doesn't break the installation for the previous Python version (I checked with Python>=3.9)
Closes #204

Fix installation in Python 3.12

---

astromodels/core/parameter.py
astromodels/tests/test_parameter.py

Closes #92 
This performs the same conversion for `min_value`/`max_value` as is was already being done for `value`.

Update Parameter bounds when changing units

---

astromodels/functions/functions_1D/powerlaws.py

The `Powerlaw_EFlux._set_units()` was setting the normalization units missing the energy part of the integrand. It should have an additional factor of `x_units` compared to `Powerlaw_flux._set_units()`.
The following code
```
from astromodels import Powerlaw_Eflux, PointSource
from astropy import units as u
l = 255.073637
b = 81.659766
a = 100. * u.keV
b2 = 10000. * u.keV
F = 0.01 * u.erg/ u.cm / u.cm / u.s
index = -1.5
spectrum = Powerlaw_Eflux(F = F.value, index = index, a = a.value, b = b2.value)
spectrum.F.unit = F.unit
spectrum.a.unit = a.unit
spectrum.b.unit = b2.unit
source = PointSource("source",         # Name of source (arbitrary, but needs to be unique)
l = l,                        # Longitude (deg)
b = b,                        # Latitude (deg)
spectral_shape = spectrum)    # …
```

Fix normalization units of Powerlaw_Eflux

---

pyproject.toml

Fix error in pyproject.toml:
Mismatched quotation marks.

Fix error in pyproject.toml

---

.readthedocs.yml

readthedocs deprecated the non-explicit use of sphinx configuration file [see here](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/)
Also updated the build OS to ubuntu 24.04 and python 3.11

Fix and update readthedocs config
