threeML/astromodels

setup.py

The original lookup for XSPEX and FITSIO libs was missing the .dylib extension. This is added here

added OSX lib lookup

---

astromodels/functions/functions.py

I added a blackbody and smoothly broken power law to the distribution. 
Also, the broken power law was discontinuous across the break. I added a normalization to patch this up.

Adding models

---

astromodels/functions/functions.py
astromodels/functions/functions_2D.py

Adding an Identity class required for linking of parameters during 3ML likelihood maximization.
Added a spatial model Ellipse_on_sphere that allows users to fit top-hat functions with an elliptical footprint.

Added Identify and Ellipse_on_sphere classes

---

astromodels/functions/functions.py

Doctored up the blackbody function so that it would stop throwing overflow warnings

stopped overflow errors in blackbody

---

astromodels/functions/functions.py

On my computer py.test is failing.
Not sure why it is failing on travisCI

Extend parameters

---

setup.py

To fix Nora's problem with gfortran installed via MacPorts

adding lookup for macports gfortran

---

setup.py

Reverts giacomov/astromodels#30

Revert "adding lookup for macports gfortran"

---

astromodels/xspec/xspec_settings.py

there was a typo in the call to xsect

fixed call to xsect

---

setup.py

The Mac problems all revolve around the FORTRAN library. This prints out a little more detail when there is a problem.

more print out info in the setup.py

---

astromodels/functions/functions_2D.py
astromodels/utils/vincenty.py

Fixed evaluate() function in the Ellipse_on_sphere() class to properly define an elliptical region on the surface of a sphere. Also added in astromodels/utils the file vincenty.py which is used to calculate the focal points of the ellipse, given its center, focal length, and orientation.

Fixed Ellipse_on_sphere()

---

astromodels/functions/function.py
astromodels/functions/priors.py
astromodels/tests/test_point_source.py

Implements a cosine prior that has equal probability over angle

added cosine prior for angular functions

---

astromodels/functions/functions_2D.py

Ellipse now takes major axis and eccentricity, rather than major and minor axis, to avoid issues in fitting where b could be larger than a.

Changed ellipse parameters: now uses eccentricity

---

astromodels/functions/functions.py

Added separate Band_grbm function to avoid having switches in the original Band function

added Band_grbm

---

astromodels/xspec/factory.py
astromodels/xspec/xspec_settings.py

I've fixed the xspec settings commands that were broken. I made the cosmology settings more user-friendly.
I have added more models to the finite difference table. We still may be missing some. I will add some xspec docs to 3ML.

Xspec fixes

---

astromodels/functions/functions_2D.py
astromodels/tests/test_functions.py

Added hash sum as dummy parameter for SpatialTemplate_2D

---

astromodels/functions/template_model.py

Added the ability to have non-logged interpolation (we are fitting in phase and magnitude.)
The default is to do log.

Linear intrp

---

astromodels/core/model.py
astromodels/tests/test_model.py

parameter_1 in link function can be either a single object or a list

Simon edit model.link

---

astromodels/functions/functions.py

The Band Calderone function was not actually changing the flux for the CPL function! This fixed that!

fixed bug in normalization

---

astromodels/core/parameter.py
astromodels/core/parameter_transformation.py
astromodels/tests/test_parameter.py

we were not testing setting bad values of transforms which cause other failures. now checked

Fix tests parameter

---

astromodels/functions/functions.py

Creates a parameter for the EBLattenuation function to vary, allowing the attenuation strength to be fit.

Add attenuation parameter to EBL in functions.py

---

astromodels/functions/template_model.py

Hdstore fix

---

.github/workflows/test_and_build.yml
ci/environment.yml

add GitHub actions to prepare for abandoning travis

Switch to actions

---

astromodels/utils/configuration.py
astromodels/utils/logging.py

Small change in logging to enable proper placement of the logs

update the logging to work with 3ml

---

astromodels/functions/functions_2D.py

**Bug fix:** Template values were unintentionally returned as integers, not floats, potentially cutting off part of the value. Now fixed.
**Enhancement:** Add a test to check if the template is normalized as expected (sum of values times pixel area in sr should be around 1). Emits a warning, not an error, because there might be a reason for an advanced user to override the template normalization.

Bug fix & enhancement to 2D template model

---

astromodels/functions/function.py
astromodels/tests/test_point_source.py

1D functions can now compute their "local spectral index" at a given energy

added ability to get the local

---

.github/workflows/test_and_build.yml
ci/environment.yml
docs/index.rst
docs/release_notes.rst

fixes CI to prepare for release. updates conda build

Prepare release

---

astromodels/xspec/factory.py
astromodels/xspec/include/sherpa/astro/xspec_extension.hh
astromodels/xspec/include/sherpa/extension.hh
astromodels/xspec/src/_xspec.cc
setup.py

Allows for choosing which XSPEC version is installed and sets a default to the one in the conda distribution

Fix xspec install

---

docs/index.rst

- Make link URL
- make list its own paragraph to render as list in html

2 minor fixes on doc front page

---

astromodels/functions/template_model.py

Removed the a duplicate assignment of self._spectrum in loading XSPEC table models.

Forgot to delete a line

---

.github/workflows/test_and_build.yml
astromodels/core/node_type.py

Fixes the issue where children are not serialized with properties when being rebuilt by parents

Fix recursion

---

astromodels/functions/functions_1D/powerlaws.py

log10 transforms for PL normalization and cutoff energies

---

astromodels/functions/functions_1D/apec.py

Change the default redshift value from 0.1 to 0.0

Change default redshift for apec

---

astromodels/functions/functions_1D/powerlaws.py

add min values to the norm of a few functions to avoid annoying warnings when importing astromodels

add min values to the norm of a few functions

---

astromodels/xspec/factory.py

Updated comments and adjusted the path for model.dat.
The original file path is not quite correct, at least it doesn't match the location after installing the latest version of heasoft.
I have changed it to prioritize checking the `$HEADAS/spectral/` path, and if not found, then to check the `$HEADAS/../spectral/` path.
[Last Pull Request](https://github.com/threeML/astromodels/pull/224) has been closed due to some fix. This version should be able to pass the flake 8 exam (but there is still some line with number of bytes greater than 79. I'm not sure wether there's any problem with this.)

Dev: Refactor find_model_dat function documentation and path
